services:
  - type: web
    name: django-simple-project
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn myproject.wsgi:application
    autoDeploy: true
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: your-production-secret-key
      - key: DATABASE_URL
        fromDatabase:
          name: django-simple-db
          property: connectionString

databases:
  - name: django-simple-db
    databaseName: djdb
    user: djuser
